FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y awscli && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY train.py .
COPY evaluate.py .
COPY retrain_if_needed.py .
COPY drift_detector.py .
COPY db/ ./db/

CMD ["python", "retrain_if_needed.py"]
