apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-app
  template:
    metadata:
      labels:
        app: inference-app
    spec:
      initContainers:
        - name: model-loader
          image: amazon/aws-cli:latest
          command:
            - aws
            - s3
            - cp
            - s3://ml-pipeline-models-tanish/models/
            - /app/models/
            - --recursive
          volumeMounts:
            - name: models-volume
              mountPath: /app/models
      containers:
        - name: inference-container
          image: 354578186384.dkr.ecr.us-east-1.amazonaws.com/ml-pipeline-inference:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "500m"
              memory: "3Gi"
          volumeMounts:
            - name: models-volume
              mountPath: /app/models
      volumes:
        - name: models-volume
          persistentVolumeClaim:
            claimName: models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  type: LoadBalancer
  selector:
    app: inference-app
  ports:
    - port: 8000
      targetPort: 8000
