apiVersion: batch/v1
kind: CronJob
metadata:
  name: retrain-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: retrain
              image: 354578186384.dkr.ecr.us-east-1.amazonaws.com/ml-pipeline-training:latest
              imagePullPolicy: Always
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: DATABASE_URL
                - name: MLFLOW_TRACKING_URI
                  value: "http://mlflow-service:5000"
                - name: INFERENCE_SERVICE_URL
                  value: "http://inference-service:8000"
                - name: MODEL_NAME
                  value: "distilbert-base-uncased"
                - name: NUM_LABELS
                  value: "2"
                - name: DATASET_NAME
                  value: "sst2"
                - name: TEXT_COLUMN
                  value: "sentence"
                - name: VAL_SPLIT
                  value: "validation"
                - name: MAX_LENGTH
                  value: "128"
                - name: EPOCHS
                  value: "3"
                - name: BATCH_SIZE
                  value: "16"
                - name: LEARNING_RATE
                  value: "2e-5"
                - name: ACCURACY_THRESHOLD
                  value: "0.80"
                - name: WEIGHT_DECAY
                  value: "0.01"
                - name: WARMUP_STEPS
                  value: "100"
                - name: GRAD_CLIP
                  value: "1.0"
                - name: PATIENCE
                  value: "3"
                - name: MAX_SAMPLES
                  value: ""
              resources:
                requests:
                  memory: "6Gi"
                  nvidia.com/gpu: "1"
                limits:
                  memory: "6Gi"
                  nvidia.com/gpu: "1"
              volumeMounts:
                - name: models
                  mountPath: /app/models

          nodeSelector:
            nvidia.com/gpu: "true"
          restartPolicy: OnFailure
          volumes:
            - name: models
              persistentVolumeClaim:
                claimName: models-pvc
